spring.config.import=optional:file:.env[.properties]

spring.application.name=bela-backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bela}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Add the driver explicitly to help Spring find it
spring.datasource.driver-class-name=org.postgresql.Driver

# Explicitly set the dialect to stop the guessing error
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# app options

app.jwt.secret=${JWT_SECRET:default_secret_1234567890_qwertyuiopasdfghjklzxcvbnm}
# 100 days in milliseconds
app.jwt.expiration-ms=8640000000