-- Baseline schema, generated by dumping what ddl-auto=update produced from the JPA
-- entities rather than written by hand, so the column names match Spring's
-- CamelCaseToUnderscoresNamingStrategy exactly. ddl-auto=validate now guards the match.
--
-- Unique-constraint names are the only deviation from the dump: Hibernate's generated
-- names (uk6dotkott2kjsp8vw4d0m25fb7 and friends) are deterministic but unreadable, and
-- validate does not compare constraint names — only tables, columns and types.

CREATE TABLE users (
    id              varchar(255) NOT NULL,
    username        varchar(255) NOT NULL,
    bio             varchar(160),
    avatar_url      varchar(255),
    country_code    varchar(2),
    email           varchar(255),
    password        varchar(255),
    auth_provider   varchar(255),
    role            varchar(255),
    created_at      timestamp(6) with time zone NOT NULL,
    updated_at      timestamp(6) with time zone NOT NULL,
    last_login_at   timestamp(6) with time zone,

    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_auth_provider_check CHECK (auth_provider IN ('LOCAL', 'ANONYMOUS')),
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

-- UserCleanupService sweeps guests hourly by exactly this pair of columns.
CREATE INDEX idx_users_auth_provider_created_at ON users (auth_provider, created_at);

-- One row per issued refresh token; rotation creates a successor sharing family_id.
--
-- user_id is deliberately a plain column with no foreign key: UserCleanupService bulk
-- deletes guest accounts, and an FK without ON DELETE CASCADE would make that sweep
-- throw. This mirrors the entity, which documents the same reasoning.
CREATE TABLE refresh_tokens (
    id              varchar(255) NOT NULL,
    token_hash      varchar(64)  NOT NULL,
    family_id       varchar(36)  NOT NULL,
    user_id         varchar(36)  NOT NULL,
    created_at      timestamp(6) with time zone NOT NULL,
    expires_at      timestamp(6) with time zone NOT NULL,
    used_at         timestamp(6) with time zone,
    revoked_at      timestamp(6) with time zone,
    rotated_to_id   varchar(36),
    user_agent      varchar(512),
    ip_address      varchar(45),

    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_tokens_user_id    ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_family_id  ON refresh_tokens (family_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
